{% set name = "hcipy" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/hcipy-{{ version }}.tar.gz
  sha256: 5c192674f64828469e1ef90c5adcd988c115826973591d6e33a1a9127224e3b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - asdf >=2.14
    - astropy-base
    - imageio
    - importlib_resources >=1.4
    - matplotlib-base >=2.0.0
    - numexpr
    - numpy
    - pillow
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - python-xxhash <4.0.0
    - ffmpeg
    - tqdm

test:
  imports:
    - hcipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ehpor/hcipy/
  summary: A framework for performing optical propagation simulations, meant for high contrast imaging, in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hcipy.org
  dev_url: https://github.com/ehpor/hcipy

extra:
  recipe-maintainers:
    - ehpor
