{% set name = "hcipy" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hcipy-{{ version }}.tar.gz
  sha256: 2add93e84802acf4c91a2ca08e61548751c7d43b6115c67698c96796ed07c6c1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  requirements:
    - asdf <=2.10 # [py<=3.7]
    - asdf # [py>3.7]
    - astropy
    - imageio
    - importlib_resources >=1.4 # [py<3.9]
    - matplotlib-base >=2.0.0
    - numexpr
    - numpy
    - pillow
    - python >=3.7
    - pyyaml
    - scipy
    - python-xxhash
    - ffmpeg

test:
  imports:
    - hcipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehpor/hcipy/
  summary: A framework for performing optical propagation simulations, meant for high contrast imaging, in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hcipy.org
  dev_url: https://github.com/ehpor/hcipy

extra:
  recipe-maintainers:
    - ehpor
