{% set name = "hcipy" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hcipy-{{ version }}.tar.gz
  sha256: 27729e7af358e2815ceb81a8d9c49e55f4015da5fb6960377daa316519e40dea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - asdf  # [py>37]
    - asdf <=2.10  # [py<=37]
    - astropy
    - imageio
    - importlib_metadata  # [py<37]
    - importlib_resources >=1.4  # [py<39]
    - matplotlib-base >=2.0.0
    - numexpr
    - numpy
    - pillow
    - python >=3.7
    - pyyaml
    - scipy
    - python-xxhash
    - ffmpeg

test:
  imports:
    - hcipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehpor/hcipy/
  summary: A framework for performing optical propagation simulations, meant for high contrast imaging, in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hcipy.org
  dev_url: https://github.com/ehpor/hcipy

extra:
  recipe-maintainers:
    - ehpor
