{% set name = "hcipy" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hcipy-{{ version }}.tar.gz
  sha256: fd28263ede152fc38a00be8a6f1337dcf17c801ace5f64901bb46e2e2792621d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - asdf <=2.10
    - astropy
    - imageio
    - importlib_resources >=1.4
    - matplotlib-base >=2.0.0
    - numexpr
    - numpy
    - pillow
    - python >=3.7
    - pyyaml
    - scipy
    - python-xxhash
    - ffmpeg

test:
  imports:
    - hcipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehpor/hcipy/
  summary: A framework for performing optical propagation simulations, meant for high contrast imaging, in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hcipy.org
  dev_url: https://github.com/ehpor/hcipy

extra:
  recipe-maintainers:
    - ehpor
