{% set name = "hcipy" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hcipy-{{ version }}.tar.gz
  sha256: fb67420308fa734a1fa258273ef0b67bd338cc66a5e918d05743331936ffe9b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - asdf <=2.10
    - astropy-base
    - imageio
    - importlib_resources >=1.4
    - matplotlib-base >=2.0.0
    - numexpr
    - numpy
    - pillow
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - python-xxhash
    - ffmpeg

test:
  imports:
    - hcipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ehpor/hcipy/
  summary: A framework for performing optical propagation simulations, meant for high contrast imaging, in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hcipy.org
  dev_url: https://github.com/ehpor/hcipy

extra:
  recipe-maintainers:
    - ehpor
